opentelemetry-collector:
  # elastic APM endpoint and APM secret_token
  extraEnvs:
    - name: ELASTIC_APM_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: elastic-secret
          key: elastic_apm_endpoint
    - name: ELASTIC_APM_SECRET_TOKEN
      valueFrom:
        secretKeyRef:
          name: elastic-secret
          key: elastic_apm_secret_token
  config:
    exporters:
      #sending everything to elastic using otlp
      otlp/elastic:
        endpoint: ${ELASTIC_APM_ENDPOINT}
        headers:
          Authorization: Bearer ${ELASTIC_APM_SECRET_TOKEN}
        compression: none
    receivers:
      # receiving otlp by grpc and http
      otlp:
        protocols:
          grpc:
          http:
            cors:
              allowed_origins:
              - http://*
              - https://*
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: 
          - batch
          - memory_limiter
          exporters: 
          - otlp/elastic
        metrics:
          receivers: 
          - otlp
          processors:
          - batch
          - memory_limiter
          exporters: [otlp/elastic]
        logs:
          receivers: [otlp]
          processors:
          - batch
          - memory_limiter
          exporters: [otlp/elastic]
      telemetry:
        #enable the telemetry on the collector itself
        resource:
          "service.name": "opentelemetry-collector"
        metrics:
          level: basic
          readers:
            # Configure a periodic metric reader.
            - periodic:
                interval: 1000
                exporter:
                  # Configure exporter to the collector itself
                  otlp:
                    protocol: http/protobuf
                    endpoint: localhost:4318
        logs:
          level: info
  #some featureGates are necessary to make it work
  featureGates: "telemetry.useOtelForInternalMetrics,telemetry.useOtelWithSDKConfigurationForInternalTelemetry,telemetry.disableHighCardinalityMetrics"
grafana:
  enabled: false

jaeger:
  enabled: false

prometheus:
  enabled: false

components:
  frontend:
    resources:
      limits:
        memory: 1Gi


